
version: '3.8'

services:
  farmos:
    image: farmos/farmos:latest
    container_name: farmos
    ports:
      - "80:80"
    volumes:
      - ./sites:/opt/drupal/web/sites
      - ./php.ini:/usr/local/etc/php/conf.d/farmos.ini
    environment:
      - DRUPAL_DB_HOST=db
      - DRUPAL_DB_NAME=FarmWorks_DB
      - DRUPAL_DB_USER=farmworks_user
      - DRUPAL_DB_PASSWORD=h08934gh!f
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: farmos_db
    environment:
      - POSTGRES_DB=FarmWorks_DB
      - POSTGRES_USER=farmworks_user
      - POSTGRES_PASSWORD=h08934gh!f
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
