<?php

/**
 * @file
 * Contains farm_import_kml.module.
 */

declare(strict_types=1);

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function farm_import_kml_help($route_name, RouteMatchInterface $route_match) {
  $output = '';

  // KML importer.
  if ($route_name == 'farm.import.kml') {
    $output .= '<p>' . t('This KML importer will create multiple Land assets from a single KML file. Select the KML file you would like to upload, as well as the default land type, then click "Parse".') . '</p>';
  }

  return $output;
}
